Alquicar_mvc/Controllers/DashboardController.cs
using Alquicar_mvc.Models;

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Alquicar_mvc.Controllers
{
    public class DashboardController : Controller
    {
        RegisterCarModels carmodel = new RegisterCarModels();
        ClienteModels cliente = new ClienteModels();
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
        //GET: tipos autos
        public ActionResult newcar()
        {
            return View();
        }
       
        //Post para salir de toda la app
        [HttpPost]
        public ActionResult salirboard() {
            Session.RemoveAll();
            return RedirectToAction("Index", "Home");
        }

        // GET: Dashboard/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Dashboard/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Dashboard/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Dashboard/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //intentos de serializar un datatable a Json sin que salga con el caracter  => \
        [HttpGet]
        //Json method for types transmition
        public JsonResult getTrasmicion()
        {
            DataTable Query = carmodel.QueryTransmition();
            return Json(ConvertDatatableToJsonNative(Query), JsonRequestBehavior.AllowGet);
        }
        //Json marcas
        // /Dashboard/getmarcas
        [HttpGet]
        public JsonResult getmarcas()
        {
            DataTable marcasdt = carmodel.QueryMarcas();
            return Json(ConvertDatatableToJsonNative(marcasdt), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getdireccion()
        {
            DataTable dirdt = carmodel.QueryDireccion();
            List<object> jsondt = ConvertDatatableToJsonNative(dirdt);
            return Json(jsondt, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult tipovehiculo()
        {
            DataTable dttipovh = carmodel.QueryTipoVehiculo();
            return Json(ConvertDatatableToJsonNative(dttipovh), JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult marcasjson()
        {
            DataTable marcasdt = carmodel.QueryMarcas();
            return Json(marcasdt, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
        public JsonResult marcasjsonresult()
        {
            DataTable marcasdt = carmodel.QueryMarcas();
            return Json(DataTableToJSONwithJsonConvert(marcasdt), "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        // json result
        public ActionResult Transmiciones()
        {
            DataTable Query = carmodel.QueryTransmition();
            return Json(Query, JsonRequestBehavior.AllowGet);
        }

        //native
        public List<object> ConvertDatatableToJsonNative(DataTable dt)
        {

            var jsontxt = new List<object>();
            //for (int i = 0; i < dt.Rows.Count; i++) {
            //    for (int j = 0; j < dt.Columns.Count; j++) {
            //        jsontxt.Add(new { dt.Columns[j].ColumnName = dt.Rows[i].ToString(), dt.Columns[j].ColumnName = dt.Rows[i].ToString() });
            //    }
            //}

            foreach (DataRow row in dt.Rows)
            {
                jsontxt.Add(new { id = row["id"].ToString(), nombre = row["nombre"].ToString() });
            }

            return jsontxt;
        }


        public static string ConvertIntoJsonwithStringBuilder(DataTable dt)
        {
            //[{"id":"1","name":}]
            var jsonString = new StringBuilder();
            if (dt.Rows.Count > 0)
            {
                jsonString.Append("[");
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    jsonString.Append("{");
                    for (int j = 0; j < dt.Columns.Count; j++)
                    {
                        jsonString.Append('"' + dt.Columns[j].ColumnName.ToString() + '"' + ":" + '"'
                            + dt.Rows[i][j].ToString() + (j < dt.Columns.Count - 1 ? "\"," : "\""));
                    }
                    jsonString.Append(i < dt.Rows.Count - 1 ? "}," : "}");
                }
                return jsonString.Append("]").ToString();
            }
            else
            {
                return "[]";
            }
        }

        public string DataTableToJSONwithJsonConvert(DataTable table)
        {
            string JSONString = string.Empty;
            JSONString = JsonConvert.SerializeObject(table);
            return JSONString;
        }

        public string DataTableToJSONWithJavaScriptSerializer(DataTable table)
        {
            JavaScriptSerializer jsSerializer = new JavaScriptSerializer();
            List<Dictionary<string, object>> parentRow = new List<Dictionary<string, object>>();
            Dictionary<string, object> childRow;
            foreach (DataRow row in table.Rows)
            {
                childRow = new Dictionary<string, object>();
                foreach (DataColumn col in table.Columns)
                {
                    childRow.Add(col.ColumnName, row[col]);
                }
                parentRow.Add(childRow);
            }
            return jsSerializer.Serialize(parentRow);
        }

        public string ConvertDataTableToJSONwithDictionary(DataTable table)
        {
            var list = new List<Dictionary<string, object>>();

            foreach (DataRow row in table.Rows)
            {
                var dict = new Dictionary<string, object>();

                foreach (DataColumn col in table.Columns)
                {
                    dict[col.ColumnName] = row[col];
                }
                list.Add(dict);
            }
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            return serializer.Serialize(list);
        }
    }
}

Alquicar_mvc/Views/Main/_layout.cshtml
@{
    try
    {
        if (Session["status"].ToString() == "")
        {
            Response.Redirect("../Account/Login");
        }
        else
        {
            <!doctype html>
            <!--
              Material Design Lite
              Copyright 2015 Google Inc. All rights reserved.

              Licensed under the Apache License, Version 2.0 (the "License");
              you may not use this file except in compliance with the License.
              You may obtain a copy of the License at

                  https://www.apache.org/licenses/LICENSE-2.0

              Unless required by applicable law or agreed to in writing, software
              distributed under the License is distributed on an "AS IS" BASIS,
              WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
              See the License for the specific language governing permissions and
              limitations under the License
            -->
            <html lang="en">
            <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
                <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
                <title>Alqicar</title>
                <!-- Add to homescreen for Chrome on Android -->
                <meta name="mobile-web-app-capable" content="yes">
                <link rel="icon" sizes="192x192" href="images/android-desktop.png">
                <!-- Add to homescreen for Safari on iOS -->
                <meta name="apple-mobile-web-app-capable" content="yes">
                <meta name="apple-mobile-web-app-status-bar-style" content="black">
                <meta name="apple-mobile-web-app-title" content="Material Design Lite">
                <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">
                <!-- Tile icon for Win8 (144x144 + tile color) -->
                <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
                <meta name="msapplication-TileColor" content="#3372DF">
                <link rel="shortcut icon" href="images/favicon.png">

                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
                <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
                @*<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css">*@
                <link href="~/Content/layout.css" rel="stylesheet" />
                <link href="~/Content/Dashboard/styles.css" rel="stylesheet" />
                <script src="~/Scripts/material.min.js"></script>
                <script src="~/Scripts/jquery-3.2.1.js"></script>
                <link href="~/Content/Proveedor/proveedor.css" rel="stylesheet" />
                <!--            alquiler and calendar  -->
                <link href="~/Content/Alquiler/alquiler.css" rel="stylesheet" />
                <!-- ref para elements select view register Auto  -->
                <link rel="stylesheet" href="https://cdn.rawgit.com/CreativeIT/getmdl-select/master/getmdl-select.min.css">
                <script defer src="https://cdn.rawgit.com/CreativeIT/getmdl-select/master/getmdl-select.min.js"></script>
            </head>
            <body>
                <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
                    <header class="demo-header mdl-layout__header mdl-color--white mdl-color-text--grey-600">
                        <div class="mdl-layout__header-row">
                            <span class="mdl-layout-title">Alquicar</span>
                            <div class="mdl-layout-spacer"></div>
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
                                <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
                                    <i class="material-icons">search</i>
                                </label>
                                <div class="mdl-textfield__expandable-holder">
                                    <input class="mdl-textfield__input" type="text" id="search">
                                    <label class="mdl-textfield__label" for="search">Enter your query...</label>
                                </div>
                            </div>
                            <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
                                <i class="material-icons">more_vert</i>
                            </button>
                            <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
                                <li class="mdl-menu__item">About</li>
                                <li class="mdl-menu__item">Contact</li>
                                <li class="mdl-menu__item">Legal information</li>
                            </ul>
                        </div>
                    </header>
                    <div class="demo-drawer mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
                        <header class="demo-drawer-header">
                            <img src="~/images/avatar.png" class="demo-avatar">
                            <div class="demo-avatar-dropdown">
                                <span>@Session["nombre_user"].ToString()</span>
                                <div class="mdl-layout-spacer"></div>
                                <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                                    <i class="material-icons" role="presentation">arrow_drop_down</i>
                                    <span class="visuallyhidden">Accounts</span>
                                </button>
                                @using (Html.BeginForm("salirboard", "Dashboard", FormMethod.Post, new { id = "logoutForm" }))
                    {
                                    <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
                                        <li class="mdl-menu__item">@Session["email"].ToString()</li>
                                        <a id="salirref" href="#" class="mdl-menu__item">salir</a>
                                        <li class="mdl-menu__item"><i class="material-icons">add</i>Add another account...</li>
                                    </ul>
                                }
                            </div>
                        </header>
                        <!--menu dinamico desde la base de datos MySql-->
                        <nav class="demo-navigation mdl-navigation mdl-color--blue-grey-800">
                            <ul class="sidebar-menu">
                                <li>
                                    <a class="mdl-navigation__link" href="~/Dashboard/Index"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">home</i>Principal</a>
                                </li>
                                @Html.Raw(@Session["menu"])

                            </ul>
                        </nav>
                    </div>
                    <main class="mdl-layout__content mdl-color--grey-100">
                        @RenderBody()
                    </main>
                </div>
                <script src="~/Scripts/Layout/MainScript.js"></script>
                <script>
                    $(document).ready(function () {
                        $("#salirref").click(function () {
                            $("#logoutForm").submit();
                        });

                        $('#registrado_por').attr("value", @Session["user_id"].ToString());
           
                        $('.select .mdl-menu__item').click(function () {

                            $inputid = $(this).attr("value");
                            $p = $("#" + $inputid).attr("value")
                            $("#" + $inputid).val($(this).attr("id"));
                        });
                    });
                </script>
            </body>

        </html>


        @*---------------------------------menu base para seguir construyendo el dinamico --------------------------
                <li>
                <a class="mdl-navigation__link" href="~/CreateRol/Create"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">domain</i>Crear Rol</a>
            </li>
            <li>
                <a class="mdl-navigation__link" href="~/CreateUser/create"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">person_add</i>Crear Usuario</a>
            </li>
            <li class="treview">
                <a class="mdl-navigation__link" id="parametricas" href="#">
                    <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">create</i>
                    <span>parametricas</span><span class="pull-right-container"><i class="fa-angle-left pull-right material-icons">keyboard_arrow_down</i></span>
                </a>
                <ul id="parametricas" class="treeview-menu">
                    <li>
                        <a class="mdl-navigation__link" href="../agregar_auto"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">directions_car</i>autos</a>
                    </li>
                </ul>
            </li>
            <li class="treview">
                <a class="mdl-navigation__link" id="query" href="#">
                    <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">equalizer</i>
                    <span>Reportes</span>
                    <span class="pull-right-container"><i class="fa-angle-left pull-right material-icons">keyboard_arrow_down</i></span>
                </a>
                <ul id="consultas" class="treeview-menu">
                    <li>
                        <a class="mdl-navigation__link" href="../cliente"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">portrait</i>Clientes</a>
                    </li>
                    <li>
                        <a class="mdl-navigation__link" href="../Alquiler"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">account_balance_wallet</i>Alquileres</a>
                    </li>
                    <li>
                        <a class="mdl-navigation__link" href="../RegisterCar"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">directions_car</i>Autos</a>
                    </li>
                </ul>
            </li>
            <li>
                <a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete_sweep</i>Deshabilitar</a>
            </li>
            <li class="treview">
                <a class="mdl-navigation__link" href="#">
                    <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">receipt</i><span>Registrar</span>
                    <span class="pull-right-container">
                        <i class="fa-angle-left pull-right material-icons">keyboard_arrow_down</i>
                    </span>
                </a>
                <ul id="registros" class="treeview-menu">
                    <li>
                        <a class="mdl-navigation__link" href="~/RegisterCar/create"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">directions_car</i>Auto</a>
                    </li>
                    <li>
                        <a class="mdl-navigation__link" href="~/Cliente/create"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">portrait</i>Cliente</a>
                    </li>
                    <li>
                        <a class="mdl-navigation__link" href="~/Proveedor/create"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">directions_walk</i>Proveedor</a>
                    </li>
                    <li>
                        <a class="mdl-navigation__link" href="~/Alquiler/create"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">account_balance_wallet</i>Alquiler</a>
                    </li>
                </ul>
            </li>
            <li>
                <a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">people</i>Social</a>
            </li>
            <div class="mdl-layout-spacer"></div>
            <li>
                <a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">help_outline</i><span class="visuallyhidden">Help</span></a>
            </li>*@
        }
    }
    catch
    {
        Response.Redirect("~/Account/Login");
    }
}