Alquicar_mvc/Controllers/CreateUserController.cs
using Alquicar_mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alquicar_mvc.Controllers
{
    public class CreateUserController : Controller
    {
        CreateUserModel user = new CreateUserModel();
        // GET: CreateUser
        public ActionResult Index()
        {       
            return View();
        }

        // GET: CreateUser/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CreateUser/Create
        public ActionResult Create()
        {
            ViewBag.permissions = user.QueryPermissions();
            ViewBag.roles = user.QueryRoles();
            return View();
        }

        // POST: CreateUser/Create
        [HttpPost]
        public ActionResult Create(CreateUserModel collectionUser)
        {
            try
            {
                user.RegisterUser(collectionUser);
                return RedirectToAction("Index", "Cliente");
                //if (ModelState.IsValid)
                //{
                   
                //}
                //else {
                //    return View();
                //}           
            }
            catch
            {
                return View();
            }
        }

        // GET: CreateUser/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CreateUser/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CreateUser/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CreateUser/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Alquicar_mvc/Views/CreateUser/Create.cshtml
@model Alquicar_mvc.Models.CreateUserModel

@{
    ViewBag.Title = "Create";
}
<div>
    <h3 class="center-text">Crear Usuario</h3>
</div>
<div class="mdl-grid demo-content">
    <div class="demo-graphs margin center content_card mdl-shadow--2dp mdl-color--white mdl-cell mdl-cell--10-col">
        @using (Html.BeginForm("Create", "CreateUser", FormMethod.Post, new { id = "UserForm" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "mdl-textfield__label" })
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>

            <div class="padding-separator-a"></div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "mdl-textfield__label" })
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "mdl-textfield__label" })
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>

            <div class="padding-separator-a"></div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth">
                <input class="mdl-textfield__input" type="text" id="r" name="r" value="Seleccione rol" readonly tabIndex="-1">
                <label for="r" class="mdl-textfield__label">Rol</label>
                <ul for="r" class="mdl-menu mdl-menu--bottom-left mdl-js-menu cuser">
                    @foreach (System.Data.DataRow row in ViewBag.roles.Rows)
                    {
                        <li class="mdl-menu__item" value=@row["permisos"].ToString() id=@row["id"].ToString()>@row["nombre"].ToString()</li>
                    }
                </ul>
            </div>
            <input style="display:none" class="mdl-textfield__input" type="text" id="Rol" name="Rol" value="waitinig">

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "mdl-textfield__label" })
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>

            <div class="padding-separator-a"></div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "mdl-textfield__label" })
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="display:none">
                @Html.LabelFor(model => model.Permissions, htmlAttributes: new { @class = "mdl-textfield__label" })
                @Html.EditorFor(model => model.Permissions, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
            </div>
        }
    </div>

    <div class="center demo-graphs content_card mdl-shadow--2dp mdl-color--white mdl-cell mdl-cell--10-col">
        <div>
            <h6 class="center-text">permisos</h6>
        </div>
        <div>
            @foreach (System.Data.DataRow row in ViewBag.permissions.Rows)
            {
                <div class="mdl-check">
                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for=@row["id"].ToString()>
                        <input type="checkbox" id=@row["id"].ToString() class="mdl-checkbox__input">
                        <span class="mdl-checkbox__label">@row["nombre"].ToString()</span>
                    </label>
                </div>
            }
        </div>

        <div class="t">
            <div class="s">
                <input type="text" value="Create" class="register_check mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect btn-form  mdl-button--colored" />
            </div>
        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        $(".cuser .mdl-menu__item").click(function () {
            $("#Rol").val($(this).attr("id"));
            $inputid = $(this).attr("value");
            var permisos = $inputid.split(",");
            var max = permisos.length;
            $("input:checkbox").each(function () {
                $(this).removeAttr("disabled");
                $(this).removeAttr("checked");
                $(this).parent().removeClass("is-checked");
                for (var i = 0; i <= max; i++) {
                    if ($(this).attr("id") === permisos[i]) {
                        $(this).parent().addClass("is-checked");
                         $(this).attr("checked", "checked");
                    }
                }
                $(this).attr('disabled', 'disabled');          
            });           
        });
        $(".register_check").click(function () {
            $("#UserForm").submit();
        });
    });
</script>