Alquicar_mvc/Controllers/AlquilerController.cs
using Alquicar_mvc.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alquicar_mvc.Controllers
{
    public class AlquilerController : Controller
    {
        AlquilerCarModel alquilerM = new AlquilerCarModel();
        // GET: Alquiler
        public ActionResult Index()
        {
            DataTable alquileres = alquilerM.QueryAlquileres();
            return View(alquileres);

        }

        // GET: Alquiler/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Alquiler/Create
        public ActionResult Create()
        {
            ViewBag.idate = "2017-05-22";
            ViewBag.fdate = "2018-05-23";
            return View();
        }


        // GET: Alquiler/Create
        public ActionResult Alquilar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Alquilar(AlquilerCarModel alquilerm)
        {
            try
            {
                if (alquilerM.RegisterAlquiler(alquilerm))
                {
                    Session["response"] = "alquiler registrado correctamente";
                    return RedirectToAction("Index", "Dashboard");
                }
                else {
                    ViewBag.response = "Error registrar el alquiler";
                    return View();
                }

                
            }
            catch
            {
                return View();
            }
        }

        // POST: Alquiler/Create
        [HttpPost]
        public ActionResult Create(string start_date, string final_date)
        {
            try 
            {
                ViewBag.Clientes = alquilerM.QueryClientes();
                ViewBag.idate = start_date;
                ViewBag.fdate = final_date;
                ViewBag.vehiculos = alquilerM.QueryVehiculos();

                return View("Alquilar");
            }
            catch
            {
                return View();
            }
        }

        // GET: Alquiler/devolucion
        public ActionResult devolucion()
        {
            return View();
        }

        [HttpPost]
        public ActionResult devolucion(string searchcar)
        {
            try
            {
                if (searchcar != null) {
                    ViewBag.querycar = alquilerM.QueryVehiculoAlquilado(searchcar);
                }
                
                return View("devolucion");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult recibido(string idcar)
        {
            try
            {
                string response = "";
                if (alquilerM.RegisterDevolucioncar(idcar))
                {
                    response = "Automovil actualizado con exito.";
                }
                else {
                    response = "Algo salio mal.";
                }
                Session["response"] = response;
                return RedirectToAction("index","Dashboard");
            }
            catch
            {
                return View();
            }
        }
        
        // GET: Alquiler/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Alquiler/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Alquiler/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Alquiler/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //Json SeekCar
        // /Alquiler/getalquiler
        [HttpGet]
        public JsonResult getcar()
        {
            DataTable seekcardt = new DataTable();
            return Json(ConvertDatatableToJsonNative(seekcardt), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult getcar(string placa)
        {
            DataTable seekcardt = new DataTable();
            return Json(ConvertDatatableToJsonNative(seekcardt), JsonRequestBehavior.AllowGet);
        }

        public List<object> ConvertDatatableToJsonNative(DataTable dt)
        {

            var jsontxt = new List<object>();
            //for (int i = 0; i < dt.Rows.Count; i++) {
            //    for (int j = 0; j < dt.Columns.Count; j++) {
            //        jsontxt.Add(new { dt.Columns[j].ColumnName = dt.Rows[i].ToString(), dt.Columns[j].ColumnName = dt.Rows[i].ToString() });
            //    }
            //}

            foreach (DataRow row in dt.Rows)
            {
                jsontxt.Add(new { id = row["id"].ToString(), nombre = row["nombre"].ToString() });
            }

            return jsontxt;
        }
    }
}

Alquicar_mvc/Views/Alquiler/Alquilar.cshtml
@model Alquicar_mvc.Models.AlquilerCarModel

@{
    ViewBag.Title = "Create";
}
<div>
    <h3 class="center-text">Alquilar Vehiculo</h3>
</div>
<div class="mdl-alquilar mdl-grid demo-content">
    <div class="select demo-graphs mdl-shadow--2dp mdl-color--white mdl-cell mdl-cell--10-col arbol">
        @using (Html.BeginForm("Create", "Alquiler", FormMethod.Post))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <!----div -->
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-pdt">
                @Html.LabelFor(model => model.start_date, htmlAttributes: new { @class = "mdl-textfield__label" })
                <input class="mdl-textfield__input" type="date" id="start" name="start" value="@ViewBag.idate">
                @Html.ValidationMessageFor(model => model.start_date, "", new { @class = "text-danger" })
            </div>

                <!----------------------------     calendar        ------------------------>
                <div id="cal" style="display:none">
                    <div class="header">
                        <span class="left button" id="prev"> &lang; </span>
                        <span class="month-year" id="label"> June 20&0 </span>
                        <span class="right button" id="next"> &rang; </span>
                    </div>
                    <table class="mdl-data-table" id="days">
                        <thead>
                            <tr>
                                <td>do</td>
                                <td>lu</td>
                                <td>ma</td>
                                <td>mi</td>
                                <td>ju</td>
                                <td>vi</td>
                                <td>sa</td>
                            </tr>
                        </thead>
                    </table>
                    <div id="cal-frame">
                        <table class="curr mdl-data-table mdl-js-data-table">
                            <tbody>
                                <tr><td class="nil"></td><td class="nil"></td><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td></tr>
                                <tr><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td class="today">11</td><td>12</td></tr>
                                <tr><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td></tr>
                                <tr><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td><td>25</td><td>26</td></tr>
                                <tr><td>27</td><td>28</td><td>29</td><td>30</td><td class="nil"></td><td class="nil"></td><td class="nil"></td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>



                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-pdt">
                    @Html.LabelFor(model => model.final_date, htmlAttributes: new { @class = "mdl-textfield__label" })
                    <input id="final" name="final" class="mdl-textfield__input" type="date" value="@ViewBag.fdate">
                </div>

                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth mdl-pdt">
                    <input class="mdl-textfield__input" type="text" id="clien" name="clien" value="Seleccione cliente" readonly tabIndex="-1">
                    <label for="clien" class="mdl-textfield__label">Cliente</label>
                    <ul for="clien" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                        @foreach (System.Data.DataRow row in ViewBag.Clientes.Rows)
                        {
                            <li class="mdl-menu__item" value="cliente_id" id=@row["id"].ToString()>@row["nombre"].ToString()</li>
                        }
                    </ul>
                </div>

                <div>
                    <div>
                        <input type="submit" id="show-dialog" value="Buscar" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" />
                    </div>
                </div>
        }
    </div>
    <div style="display:none">
        @using (Html.BeginForm("alquilar", "Alquiler", FormMethod.Post, new { id = "alquilarForm" }))
        {
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-pdt" style="display:none">
                @Html.LabelFor(model => model.car_id, htmlAttributes: new { @class = "mdl-textfield__label" })
                @Html.EditorFor(model => model.car_id, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                @Html.ValidationMessageFor(model => model.car_id, "", new { @class = "text-danger" })
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-pdt" style="display:none">
                @Html.LabelFor(model => model.cliente_id, htmlAttributes: new { @class = "mdl-textfield__label" })
                @Html.EditorFor(model => model.cliente_id, new { htmlAttributes = new { @class = "mdl-textfield__input"} })
                @Html.ValidationMessageFor(model => model.cliente_id, "", new { @class = "text-danger" })
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-pdt" style="display:none">
                @Html.LabelFor(model => model.registrador_por, htmlAttributes: new { @class = "mdl-textfield__label" })
                @Html.EditorFor(model => model.registrador_por, new { htmlAttributes = new { @class = "mdl-textfield__input", @value = "@Session['user_id'].ToString()" } })
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-pdt">
                @Html.LabelFor(model => model.start_date, htmlAttributes: new { @class = "mdl-textfield__label" })
                <input class="mdl-textfield__input" type="date" id="start_date" name="start_date" value="@ViewBag.idate">
                @Html.ValidationMessageFor(model => model.start_date, "", new { @class = "text-danger" })
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-pdt">
                @Html.LabelFor(model => model.final_date, htmlAttributes: new { @class = "mdl-textfield__label" })
                <input id="final_date" name="final_date" class="mdl-textfield__input" type="date" value="@ViewBag.fdate">
                @Html.ValidationMessageFor(model => model.final_date, "", new { @class = "text-danger" })
            </div>
        }
    </div>


    <dialog class="mdl-dialog">
        <h4 class="mdl-dialog__title">Alquilar</h4>
        <div id="alquilercont" class="mdl-dialog__content">
            <p id="price_day"></p>
            <p id="price_final"></p>
            <p id="car" style="display:none"></p>
        </div>
        <div class="mdl-dialog__actions">
            <button type="button" class="mdl-button accept">aceptar</button>
            <button type="button" class="mdl-button close">cancelar</button>
        </div>
    </dialog>


    <div id="modalyes" style="display:none" class="demo-card-event mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand">
            <h4>Alquilar vehiculo</h4>
        </div>
        <div class="mdl-card__supporting-text">
            Desea alquilar este vehiculo?
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <button id="acceptmdl" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                aceptar
            </button>
            <div class="mdl-layout-spacer"></div>
            <button id="canelarmdl" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                cancelar
            </button>
        </div>

    </div>
    @if (ViewBag.vehiculos != null)
    {
        foreach (System.Data.DataRow row in ViewBag.vehiculos.Rows)
        {

            <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
                <header class="section__play-btnr mdl-cell mdl-cell--5-col-desktop mdl-cell--2-col-tablet mdl-cell--4-col-phone  mdl-color-text--white">
                    <img width="210" height="210" src="@row["foto"].ToString()" />
                </header>
                <div class="mdl-card mdl-cell mdl-cell--7-col-desktop mdl-cell--6-col-tablet mdl-cell--4-col-phone">
                    <div class="mdl-card__title">
                        <h2 class="mdl-card__title-text">@row["modelo"].ToString()</h2>
                    </div>
                    <div class="md-caracteristicas mdl-card__supporting-text">
                        <div><label>Tipo</label><label class="izq">@row["tipo"].ToString()</label></div>
                        <div><label>Direccion</label><label class="izq">@row["direccion"].ToString()</label></div>
                        <div><label>Transmicion</label><label class="izq">@row["transmicion"].ToString()</label></div>
                        <div><label>Marca</label><label class="izq">@row["marca"].ToString()</label></div>
                        <div class="price"><label>precio final por dia</label><label class="izq @row["id"].ToString()">$@row["precio_dia"].ToString()</label></div>
                    </div>
                    <div class="mdl-card__actions cars">
                        <a href="#" id="@row["id"].ToString()" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored">Alquilar</a>
                    </div>
                </div>
            </section>
        }
    }
</div>
<script>
    $(document).ready(function () {
        min_date_return();
        dayalquiler();
        launchModal();
        alquilar();
    });

    function launchModal() {
        $('.cars .mdl-button').click(function () {
            var p = $(this).attr("id");
            var price = $("." + p).text();
            $('#car').text(p);
            var fecha_in = $('#start').val().split("-");
            var fecha_fn = $('#final').val().split("-");
            var total = cal_days(fecha_fn[2], fecha_in[2]) * parseInt(price.substring(1));
            $('#price_day').text("Precio dia: " + price);
            $('#price_final').text("Precio final: $" + total);
            modalaux();
        });
    }

    function alquilar() {
        $('.accept').click(function () {
            $('#car_id').attr("value", $('#car').text());;
            $('#registrador_por').attr("value",@Session["user_id"]);
            //$('#cliente_id').attr("value",$('#clien').attr("id"));
            $('#start_date').attr("value",$('#start').val());
            $('#final_date').attr("value",$('#final').val());
            $('#alquilarForm').submit();
        });
    }

    function cal_days(daya, dayb) {
        return r = parseInt(daya) - parseInt(dayb)      
    }

    function modalaux() {

        var dialog = document.querySelector('dialog');
        if (!dialog.showModal) {
            dialogPolyfill.registerDialog(dialog);
        }
        dialog.showModal();

        dialog.querySelector('.close').addEventListener('click', function () {
            dialog.close();
        });

    }

    function dayalquiler() {
        $dateone = $('#start').val();
        var f = new Date();
        var month = monthcurrent(f.getMonth());
        var day = daycurrent(f.getDate());
        var initalDate = f.getFullYear() + "-" + month + "-" + day;
        $('#start').attr({ "value": $dateone, "min": initalDate });
    }
    
    function monthcurrent(month) {
        if (month > 10) {
            return month + 1;
        } else {
            return "0" + (month + 1);
        }
    }

    function daycurrent(day) {
        if (day < 10) {
            return "0" + day;
        } else {
            return day;
        }
    }

    function min_date_return() {
        $('#final').click(function () {
            $minimal = $('#start').val().split("-");
            var fecha = parseInt($minimal[2])+1;
            var min = $minimal[0]+"-" + $minimal[1] +"-"+ daycurrent(fecha);
            $($(this)).attr({"value":min,"min": min});
        });
    }
</script>

Alquicar_mvc/Views/Alquiler/Index.cshtml
@{
    ViewBag.Title = "Index";
    int cont = 1;
    int contcel = 1;
}

<div class="mdl-grid demo-content">
    <div class="center">
        <table class="mdl-data-table mdl-js-data-table">
            <thead>
                <tr>
                    <th class="mdl-data-table__cell--non-numeric">num</th>
                    @foreach (System.Data.DataColumn col in Model.Columns)
                    {
                        if (@col.Caption != "id")
                        {
                            <th class="mdl-data-table__cell--non-numeric"> @col.Caption</th>
                        }

                    }
                    <th class="mdl-data-table__cell--non-numeric"> opciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (System.Data.DataRow row in Model.Rows)
                {
                    <tr>
                        <td class="mdl-data-table__cell--non-numeric">@cont</td>
                        @foreach (var cell in row.ItemArray)
                        {
                            if (@contcel < row.ItemArray.Length)
                            {
                                <td class="mdl-data-table__cell--non-numeric"> @cell.ToString() </td>
                            }
                            else
                            {
                                contcel = 0;
                                <td class="mdl-data-table__cell--non-numeric"> @Html.ActionLink("Details", "Details", new { id = @cell.ToString() })  </td>
                            }
                            contcel = contcel + 1;

                        }


                    </tr>
                    cont = cont + 1;

                }
            </tbody>
        </table>
    </div>
</div>

Alquicar_mvc/Views/Alquiler/devolucion.cshtml
@model Alquicar_mvc.Models.AlquilerCarModel

@{
    ViewBag.Title = "devolucion";
}
<div>
    <h3 class="center-text">Devolucion de vehiculo</h3>
</div>

<div class="mdl-grid demo-content">
    <div class="select demo-graphs  center mdl-color--white mdl-cell mdl-cell--8-col-desktop">
        @using (Html.BeginForm())
        {
            <div class="buscar">
                <span>Buscar  auto por placa</span>
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
                    <label class="mdl-button mdl-js-button mdl-button--icon" for="searchcar">
                        <i class="material-icons">search</i>
                    </label>
                    <div class="mdl-textfield__expandable-holder">
                        <input class="mdl-textfield__input" type="text" name="searchcar" id="searchcar">
                        <label class="mdl-textfield__label" for="searchcar">Enter your query...</label>
                    </div>
                </div>
            </div>
            <div>
                <div>
                    <input type="submit" id="show-dialog" value="Buscar" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" />
                </div>
            </div>
                @*<dl class="dl-horizontal">*@
                @*<dt class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <label class="mdl-textfield__label">@Html.DisplayNameFor(model => model.start_date)</label>
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.start_date)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.final_date)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.final_date)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.car_id)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.car_id)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.cliente_id)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.cliente_id)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.registrador_por)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.registrador_por)
                        </dd>
                    </dl>*@
        }

    </div>

    @if (ViewBag.querycar != null)
    {

        <div class="select demo-graphs  center mdl-color--white mdl-cell mdl-cell--8-col-desktop">
            @using (Html.BeginForm("recibido", "Alquiler", FormMethod.Post))
            {
                foreach (System.Data.DataRow row in ViewBag.querycar.Rows)
                {
                    <input class="mdl-textfield__input" style="display:none" type="text" id="idcar" name="idcar" value=@row["idcar"].ToString()>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.start_date)
                        </dt>

                        <dd>
                            @row["fecha_alquiler"].ToString()
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.final_date)
                        </dt>

                        <dd>
                            @row["fecha_devolucion"].ToString()
                        </dd>
                        <dt>
                            Modelo
                        </dt>

                        <dd>
                            @row["modelo"].ToString()
                        </dd>

                        <dt>
                            tipo
                        </dt>

                        <dd>
                            @row["tipo"].ToString()
                        </dd>

                        @*<dt>
                                @Html.DisplayNameFor(model => model.registrador_por)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.registrador_por)
                            </dd>*@
                        <dt>
                            marca
                        </dt>
                        <dd>
                            @row["marca"].ToString()
                        </dd>
                        <dt>
                            cliente
                        </dt>
                        <dd>
                            @row["nombre"].ToString()
                        </dd>
                        <dt>
                            identificacion
                        </dt>
                        <dd>
                            @row["identificacion"].ToString()
                        </dd>
                        <dt>
                            <img width="210" height="210" src="@row["foto"].ToString()" />
                        </dt>
                    </dl>
                }
                <div>
                    <div>
                        <input type="submit" id="recibircar" value="Aceptar" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" />
                    </div>
                </div>
            }
        </div>

    }

</div>



            @*<p>
                @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
                @Html.ActionLink("Back to List", "Index")
            </p>*@