Alquicar_mvc/Controllers/RegisterCarController.cs
using Alquicar_mvc.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alquicar_mvc.Controllers
{
    public class RegisterCarController : Controller
    {
        RegisterCarModels carmodel = new RegisterCarModels();
        ClienteModels cliente = new ClienteModels();
        // GET: RegisterCar
        public ActionResult Index()
        {
            DataTable autos = carmodel.QueryCurrentCars();
            return View(autos);
        }

        // GET: RegisterCar/Details/5
        public ActionResult Details(int id)
        {
            DataTable detallecar = carmodel.QueryDetalleCar(id);
            return View(detallecar);
        }

        // GET: RegisterCar/Create
        public ActionResult Create()
        {
            ViewBag.proveedores = carmodel.QueryProveedor();
            ViewBag.vehiculos = carmodel.QueryTipoVehiculo();
            ViewBag.direcciones = carmodel.QueryDireccion();
            ViewBag.marcas = carmodel.QueryMarcas();
            ViewBag.transmicion = carmodel.QueryTransmition();
            return View();
        }

        // POST: RegisterCar/Create
        [HttpPost]
        public ActionResult Create(RegisterCarModels car,HttpPostedFileBase vehiculoimg)
        {
            try
            {
               
                if (vehiculoimg != null)
                {               
                    if (ModelState.IsValid)
                    {
                        string img = Path.GetFileName(vehiculoimg.FileName);
                        string ruta = "../images/vehiculos/" + img;
                        string carpeta = Path.Combine(Server.MapPath("~/images/vehiculos"), img);
                        if (carmodel.RegistrarCar(car, ruta))
                        {
                            vehiculoimg.SaveAs(carpeta);
                            Session["response"] = "Auto registrado correctamente";
                            return RedirectToAction("index", "Dashboard");
                        }
                        else {
                            ViewBag.response = "Error! algo salio mal";
                            return View();
                        }
                    }
                    else
                    {
                        return View();
                    }
                }
                else {
                    ViewBag.errorimg = "no has seleccionado una imagen";
                    return View();
                }
            }
            catch(Exception exc)
            {
                ViewBag.response = "Error! algo salio mal";
                return View();
            }
        }
       
        // GET: RegisterCar/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RegisterCar/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RegisterCar/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RegisterCar/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Alquicar_mvc/Views/RegisterCar/Create.cshtml
@model Alquicar_mvc.Models.RegisterCarModels
@{
    ViewBag.Title = "Create";
}
<div>
    <h3 class="center-text">Registrar Automovil</h3>
</div>

<div class="mdl-grid demo-content">
    <div class="select demo-graphs center mdl-shadow--2dp mdl-color--white mdl-cell mdl-cell--8-col">
        @using (Html.BeginForm("create","RegisterCar",FormMethod.Post, new {enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            // ------------- proveedores ---------------------
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth">        
                <input class="mdl-textfield__input" type="text" id="proveedor" name="proveedor" value="selecione" readonly tabIndex="-1">
                <label for="proveedor" class="mdl-textfield__label">Propietario</label>
                <ul for="proveedor" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    @foreach (System.Data.DataRow row in ViewBag.proveedores.Rows)
                    {
                        <li class="mdl-menu__item" value="proveedor_car" id=@row["id"].ToString()>@row["nombre"].ToString()</li>
                    }
                </ul>
            </div>
            <div class="padding-separator"></div>
            //---------- tipo de vehiculo ----------
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth">
                <input class="mdl-textfield__input" type="text" id="tipo_vehiculos" name="tipo_vehiculos" value="selecione" readonly tabIndex="-1">
                <label for="tipo_vehiculos" class="mdl-textfield__label">Tipo de auto</label>
                <ul for="tipo_vehiculos" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    @foreach (System.Data.DataRow row in ViewBag.vehiculos.Rows)
                    {
                        <li class="mdl-menu__item" value="tipo_vehiculo" id=@row["id"].ToString()>@row["nombre"].ToString()</li>
                    }
                </ul>
            </div>
   
            //-------------- direccion  ----------------
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth">
                <input class="mdl-textfield__input" type="text" id="tipo_direccions" name="tipo_direccions" value="selecione" readonly tabIndex="-1">
                <label for="tipo_direccions" class="mdl-textfield__label">Direccion</label>
                <ul for="tipo_direccions" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    @foreach (System.Data.DataRow row in ViewBag.direcciones.Rows)
                    {
                        <li class="mdl-menu__item" value="tipo_direccion" id=@row["id"].ToString()>@row["nombre"].ToString()</li>
                    }
                </ul>
            </div>
            <div class="padding-separator"></div>
            //---------------------- tipo trasmiciones  ------------
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth">
                <input class="mdl-textfield__input" type="text" id="tipo_trasmicione" name="tipo_trasmicione" value="selecione" readonly tabIndex="-1">
                <label for="tipo_trasmicione" class="mdl-textfield__label">Transmicion</label>
                <ul for="tipo_trasmicione" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    @foreach (System.Data.DataRow row in ViewBag.transmicion.Rows)
                    {
                        <li class="mdl-menu__item" value="tipo_trasmicion" id=@row["id"]>@row["nombre"].ToString()</li>
                    }
                </ul>
            </div>
            
            //------------- marca ---------------
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth">
                <input class="mdl-textfield__input" type="text" id="marcax" name="marcax" value="selecione marca" readonly tabIndex="-1">
                <label for="marcax" class="mdl-textfield__label">Marcas</label>
                <ul for="marcax" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    @foreach (System.Data.DataRow row in ViewBag.marcas.Rows)
                    {
                        <li class="mdl-menu__item" value="marca" id=@row["id"].ToString()> @row["nombre"].ToString()</li>
                    }
                </ul>
            </div>
            <div class="padding-separator"></div>
            @*<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="text" id="gama" name="gama">
                    <label class="mdl-textfield__label" for="nombre">Gama</label>
                </div>*@
        
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="text" id="color" name="color">
                    <label class="mdl-textfield__label" for="nombre">Color</label>
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" id="cilindraje" name="cilindraje">
                <label class="mdl-textfield__label" for="nombre">Cilindraje</label>
            </div>
            <div class="padding-separator"></div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" id="modelo" name="modelo">
                <label class="mdl-textfield__label" for="nombre">Modelo</label>
            </div>


            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" id="descripcion" name="descripcion">
                <label class="mdl-textfield__label" for="n">Descripcion</label>
            </div>
            <div class="padding-separator"></div>
            @*<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="text" id="tipo_combustible" name="tipo_combustible">
                    <label class="mdl-textfield__label" for="nombre">Tipo combustible</label>
                </div>*@

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" id="placa" name="placa">
                <label class="mdl-textfield__label" for="c">placa</label>
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                @Html.LabelFor(model => model.kilomentros, htmlAttributes: new { @class = "mdl-textfield__label" })
                @Html.EditorFor(model => model.kilomentros, new { htmlAttributes = new { @class = "mdl-textfield__input", @value = "@Session['user_id'].ToString()" } })
                @Html.ValidationMessageFor(model => model.kilomentros, "", new { @class = "text-danger" })
            </div>
            <div class="padding-separator"></div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" id="precio_pago" name="precio_pago">
                <label class="mdl-textfield__label" for="precio_pago">Valor pago mensual</label>
            </div>

            <div class="mdl-textfield">
                <input type="file" id="vehiculoimg" name="vehiculoimg">
            </div>
            <input style="display:none" class="mdl-textfield__input" type="text" id="registrado_por" name="registrado_por" value="employ">
            <input style="display:none" class="mdl-textfield__input" type="text" id="proveedor_car" name="proveedor_car" value="waiting">
            <input style="display:none" class="mdl-textfield__input" type="text" id="tipo_vehiculo" name="tipo_vehiculo" value="vehiculos">
            <input style="display:none" class="mdl-textfield__input" type="text" id="tipo_direccion" name="tipo_direccion" value="dirreccion">
            <input style="display:none" class="mdl-textfield__input" type="text" id="tipo_trasmicion" name="tipo_trasmicion" value="trans">
            <input style="display:none" class="mdl-textfield__input" type="text" id="marca" name="marca" value="marca">
            <div>
                 <div>
                      <input id="register_car" type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect btn-form  mdl-button--colored" onclick="chekear()" />
                 </div>
             </div>
        }
    </div>
  
</div>

Alquicar_mvc/Views/RegisterCar/Details.cshtml
@*@model Alquicar_mvc.Models.AlquilerCarModel*@

@{
    ViewBag.Title = "Details";
}
<div>
    <h3 class="center-text">Details</h3>
</div>

<div class="mdl-grid demo-content">
    <div class="select demo-graphs  center mdl-color--white mdl-cell mdl-cell--8-col-desktop">

        <hr />
        <dl class="dl-horizontal">

            @foreach (System.Data.DataColumn col in Model.Columns)
            {

                <dt class="mdl-data-table__cell--non-numeric"> @col.Caption</dt>
                if (@col.Caption == "disponible")
                {
                    if (@Model.Rows[0][@col.Caption].ToString() == "0")
                    {
                        <dd class="mdl-data-table__cell--non-numeric">No Disponible</dd>
                    }
                    else
                    {
                        <dd class="mdl-data-table__cell--non-numeric">Disponible</dd>
                    }


                }
                else if (@col.Caption == "foto")
                {
                    <dd class="mdl-data-table__cell--non-numeric">
                        <img width="210" height="210" src=@Model.Rows[0][@col.Caption].ToString() />
                    </dd>
                }
                else
                {
                    <dd class="mdl-data-table__cell--non-numeric"> @Model.Rows[0][@col.Caption].ToString() </dd>
                }


            }


            @*<dt>
                    @Model.Columns[0].ToString()
                </dt>

                <dd>
                    @Model.Rows[0][@Model.Columns[0].ToString()].ToString()
                </dd>

                <dt>
                   @Model.Columns[1].ToString()
                </dt>

                <dd>
                    @Model.Rows[0][@Model.Columns[1].ToString()].ToString()
                </dd>

                <dt>
                   @Model.Columns[2].ToString()
                </dt>

                <dd>
                    @Model.Rows[0][@Model.Columns[2].ToString()].ToString()
                </dd>

                <dt>
                   @Model.Columns[3].ToString()
                </dt>

                <dd>
                   @Model.Rows[0][@Model.Columns[3].ToString()].ToString()
                </dd>

                <dt>
                   @Model.Columns[4].ToString()
                </dt>

                <dd>
                    @Model.Rows[0][@Model.Columns[4].ToString()].ToString()
                </dd>

        </dl>*@
    </div>
</div>

Alquicar_mvc/Views/RegisterCar/Index.cshtml
@{
    ViewBag.Title = "Index";
    int cont = 1;
    int contcel = 1;
    
}

<div  class="mdl-grid demo-content">
    <div class="center">
        <table class="mdl-data-table mdl-js-data-table">
            <thead>
                <tr>
                    <th class="mdl-data-table__cell--non-numeric">num</th>
                    @foreach (System.Data.DataColumn col in Model.Columns)
                    {
                        if (@col.Caption != "id")
                        {
                            <th class="mdl-data-table__cell--non-numeric"> @col.Caption</th>
                        }

                    }
                    <th class="mdl-data-table__cell--non-numeric"> opciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (System.Data.DataRow row in Model.Rows)
                {
                    <tr>
                        <td class="mdl-data-table__cell--non-numeric">@cont</td>
                        @foreach (var cell in row.ItemArray)
                        {
                            if (@contcel < row.ItemArray.Length)
                            {
                                <td class="mdl-data-table__cell--non-numeric"> @cell.ToString() </td>
                            }
                            else
                            {
                                contcel = 0;
                                <td class="mdl-data-table__cell--non-numeric"> @Html.ActionLink("Details", "Details", new { id = @cell.ToString() })  </td>
                            }
                            contcel = contcel + 1;

                        }

                        
                    </tr>
                    cont = cont + 1;

                }
            </tbody>
        </table>
    </div>
</div>